-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Create the 'test' table
create table if not exists public.test (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    content text
);

-- Insert a sample row to verify connection
insert into public.test (content)
values ('Hello from Supabase!')
on conflict do nothing;
